### PR TITLE
spi: allow impls returning early, add flush. 

### LINKED ISSUE #264: Clarify SPI timing behaviour (currently completely broken!)
### TLDR
Currently, it is unclear when exactly the SPI transfer functions return. Some drivers assume that the functions return after the clock line has returned to idle state. This is not how some (most?) HALs implement SPI. The documentation should clarify the expected behaviour.

### The Problem
I am currently building an application with [https://github.com/astro/embedded-nrf24l01](embedded-nrf24l01) on a system with an STM32F429 clocked at 168 MHz. I clocked the SPI bus at 500 KHz -- much slower than the system clock, which to a certain degree caused the following problems -- and subsequently saw very weird behaviour. embedded-nrf24l01 would pull the CS pin high and then low again *before the SCK signal reached idle*, so the device only ever registered one single long transfer instead of multiple small transfers as required to send individual commands. All but the first command was therefore ignored or incorrectly processed by the device.

The corresponding code in embedded-nrf24l01 is as follows:

        self.csn.set_low().unwrap();
        let transfer_result = self.spi.transfer(buf).map(|_| {});
        self.csn.set_high().unwrap();

Changing the code as follows solves all problems, because then all CS changes occur while the SPI bus is idle:

        cortex_m::asm::delay(200);
        self.csn.set_low().unwrap();
        cortex_m::asm::delay(200);
        let transfer_result = self.spi.transfer(buf).map(|_| {});
        cortex_m::asm::delay(200); // <- this line is what fixes the problem, the other delays are just to make the signal look more like in the datasheet
        self.csn.set_high().unwrap();

### The Solution(s)

1. The documentation could state that the SPI functions return as soon as the last bit was read from the bus. Device drivers would then have to add delays where necessary, similar to the code above. I do not know how many devices would require this type of delay -- if many devices need it, this solution is a *huge* footgun and substantially increases complexity. I hardcoded the delay cycles in the example above, but that's only possible because I know the clock speed of the device.
2. The documentation could state that the SPI functions return as soon as the SCK signal is idle again. Probably, all HALs would have to be modified.

### Other Problems
If I understand it correctly, this bug is not completely identical to https://github.com/stm32-rs/stm32f0xx-hal/issues/130, although that ticket shows a similar problem with SPI documentation: The documentation should (or should not?) state that transfer() finishes after the last bit has been transferred, not after the bits have been shoved into a FIFO.

### PR DESCRIPTION
**Pull request by Dirbaio**
Fixes #264 
Depends on #351 

- Document that all methods may return early, before bus is idle.
- Add a `flush` method to wait for bus to be idle.

The alternative is to document that methods MUST wait for bus idle before returning, but that would be bad for performance IMO. Allowing early return means multiple successive writes can "overlap" so that bytes come out back-to-back without gaps, which is great for workloads with tons of small writes, like SPI displays with `embedded-graphics`.

Drivers using `SpiDevice` won't have to worry about this, it'll Just Work since Device impls must flush before deasserting CS. Drivers using SpiBus will have to care if they coordinate SPI activity with other GPIO activity.

### CODE REVIEW

**Comment by ryankurte** [comment]
a [diff](https://github.com/embassy-rs/embedded-hal/compare/spi-transaction...spi-flush) against #351 so this is easier to review pre that landing

File: src/spi/blocking.rs [hunk 1]
```diff
@@ -1,108 +1,338 @@
...
+//! benefits. (There's no point in a HAL implementing [`SpiDevice`] if the CS management is software-only, this task is better left to
+//! the HAL-independent implementations).
+//!
+//! HALs **must not** add infrastructure for sharing at the [`SpiBus`] level. User code owning a [`SpiBus`] must have the guarantee
+//! of exclusive access.
+//!
+//! # Flushing
+//!
+//! To improve performance, Bus implementations are allowed to return before the operation is finished, i.e. when the bus is still not
+//! idle. You must call [`flush`](SpiBusFlush::flush) to wait for operations to actually finish, for example before deasserting CS in a
```
Comment (ryankurte) [inline src/spi/blocking.rs:135]: i'm not sure exactly how to reframe this but, it might be nice to separate the `Bus` and `Device` components, something like:

```suggestion
//! idle. When using a `Bus` directly if you need to ensure the bus is idle you can manually call [`flush`](SpiBusFlush::flush).
//!  [`SpiDevice`] implementations **must** call [`flush`](SpiBusFlush::flush) prior to de-asserting CS to maintain ordering guarantees.
```

Comment (Dirbaio) [reply src/spi/blocking.rs:135]: You may still have to flush even if using a SpiDevice, for example in an SPI display to ensure the DCX pin toggles at the right time wrt the spi data. It's rare though....

File: src/spi/blocking.rs [hunk 2]
```diff
@@ -1,108 +1,338 @@
...
+//! [`SpiDevice`] implementation, or before deinitializing the hardware SPI peripheral.
+//!
+//! For example, for [`write`](SpiBusWrite::write) operations, it is common for hardware SPI peripherals to have a small
+//! FIFO buffer, usually 1-4 bytes. Software writes data to the FIFO, and the peripheral sends it on MOSI at its own pace,
+//! as the specified SPI frequency. It is allowed or an implementation of [`write`](SpiBusWrite::write) to return as soon
```
Comment (adamgreig) [inline src/spi/blocking.rs:140]:
```suggestion
//! at the specified SPI frequency. It is allowed for an implementation of [`write`](SpiBusWrite::write) to return as soon
```

File: src/spi/blocking.rs (hunk 1 above)
Comment (ryankurte) [reply src/spi/blocking.rs:147]:
```
, while [`SpiDevice`] users may choose to flush within an transaction if required.
```

**Comment by Dirbaio** [comment]
New version

- Rebased on master
- Expanded docs on when flush might be needed.

File: src/spi/blocking.rs (hunk 1 above)
Comment (Dirbaio) [reply src/spi/blocking.rs]: I've expanded docs on when flush might be needed, hopefully it's much straightforward now!

**Review by ryankurte — APPROVED** [review]
lgtm~! any other comments @hal? it'd be good to get this merged before too many folks refactor their SPI impls.

File: src/spi/blocking.rs [hunk 3]
```diff
@@ -140,6 +140,32 @@
 //!
 //! HALs **must not** add infrastructure for sharing at the [`SpiBus`] level. User code owning a [`SpiBus`] must have the guarantee
 //! of exclusive access.
+//!
+//! # Flushing
+//!
+//! To improve performance, Bus implementations are allowed to return before the operation is finished, i.e. when the bus is still not
```
Comment (eldruin) [inline src/spi/blocking.rs:146]:
```suggestion
//! To improve performance, [`SpiBus`] implementations are allowed to return before the operation is finished, i.e. when the bus is still not
```

**Review by eldruin — COMMENTED** [review]
Other the nitpick below, looks good to me!

**Review by eldruin — APPROVED** [review]
Thank you!

**Review by therealprof — APPROVED** [review]
LGTM, too.

bors r+
